### ISSUE TITLE
Sample feedback: display-test-ad/js

### ISSUE THREAD

**Issue by you1cheng** [googleads/google-publisher-tag-samples#40]
https://googleads.github.io/google-publisher-tag-samples/display-test-ad/js/demo.html

The test demo doesn't work, there are errors on the console

browser: chrome
version: 109.0.5414.87

**Comment by you1cheng** [comment]
> Hi @you1cheng, what errors are you seeing in the console? I'm testing with the same version of Chrome but the sample seems to be working fine without errors.

pubads_impl_2023010501.js:10 Error: s:0 rs:4
    at Vh.d.onerror (gpt.js:10:38117)
    
On the incognito mode, it works, and no this error

**Comment by jimper** [comment]
It sounds like the issue might be related to your environment, especially if the page works in incognito mode. Do you have any extensions enabled that could be interfering with the GPT ad script?

**Comment by you1cheng** [comment]
@jimper I found the extension, it's an ad blocker, thank you

**Comment by you1cheng** [comment]
@jimper hi, can I ask you a question?
I run the demo on this page (https://developers.google.com/publisher-tag/guides/get-started), and it works on my local env, but when I replace the params in googletag.defineSlot() method with my website's, it can't work locally, do you know the reason about it?

**Comment by jimper** [comment]
Hi @you1cheng, I wouldn't be able to help without a live example. Can you reproduce the issue in a sandbox like [JSFiddle](https://jsfiddle.net/)? If not, it may be something specific to your local environment again.

**Comment by you1cheng** [comment]
@jimper hi, it's my bad, here is it: https://jsfiddle.net/jcp9wq6r/5/

**Comment by jimper** [comment]
This is probably due to a configuration issue on the Ad Manager side. If you check the [publisher console](https://developers.google.com/publisher-tag/guides/publisher-console), you can see that an ad is being requested ("Ad fetch count: 1"), but nothing is returned from Ad Manager ("Ad unit did not fill").

You can try following the Delivery Diagnostics link in the publisher console for more info. If that doesn't help you identify the issue, you can contact product support from the [Ad Manager community forums](https://support.google.com/admanager/community).

**Comment by you1cheng** [comment]
yes, I solved the issue, thank you @jimper
