### ISSUE TITLE
Sample feedback: display-web-interstitial-ad/js

### ISSUE THREAD

**Issue by tss-legal-code** [googleads/google-publisher-tag-samples#91]
no ad is loaded, but I see message in the console:

pubads_impl.js?cb=31083530:24 [GPT] Interstitial /6355419/Travel/Europe/France/Paris not requested: Unable to access local storage to determine if the frequency cap has been exceeded due to insufficient user consent.

maybe demo example should be supplied with some consent management script ?

**Comment by jimper** [comment]
Hi @tss-legal-code, since the sample doesn't include a consent management script, GPT should be operating under the assumption that gathering user consent isn't necessary. That means that the error you're seeing is likely due to the browser itself (or maybe an extension like an ad blocker) blocking access to local storage.
